module.exports = {
  itin: { name: 'sampleName' },
  events: [{
    id: 'v1Lpwqs75mmQ0ugugoqTvA',
    alias: 'tower-of-london-london-2',
    name: 'Tower of London',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/6pfXuqHEfHBbWld3ZectIg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/tower-of-london-london-2?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 547,
    categories: [{ alias: 'landmarks', title: 'Landmarks & Historical Buildings' }],
    rating: 4.5,
    coordinates: { latitude: 51.5083008269638, longitude: -0.0760689389286426 },
    transactions: [],
    location: {
      address1: 'Tower Hill', address2: '', address3: '', city: 'London', zip_code: 'EC3N 4AB', country: 'GB', state: 'XGL', display_address: ['Tower Hill', 'London EC3N 4AB', 'United Kingdom'],
    },
    phone: '+442031666000',
    display_phone: '+44 20 3166 6000',
    distance: 4174.992612672871,
    userRating: 1,
  }, {
    id: 'NPAkaFjtmDC8IKC60u5PAw',
    alias: 'coca-cola-london-eye-london',
    name: 'Coca Cola London Eye',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/KeNmtKQsaljr5q7u92r3WQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/coca-cola-london-eye-london?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 882,
    categories: [{ alias: 'localflavor', title: 'Local Flavor' }, { alias: 'landmarks', title: 'Landmarks & Historical Buildings' }],
    rating: 4,
    coordinates: { latitude: 51.503364, longitude: -0.11957 },
    transactions: [],
    location: {
      address1: 'Riverside Building', address2: 'County Hall', address3: 'Westminster Bridge Road', city: 'London', zip_code: 'SE1 7PB', country: 'GB', state: 'XGL', display_address: ['Riverside Building', 'County Hall', 'Westminster Bridge Road', 'London SE1 7PB', 'United Kingdom'],
    },
    phone: '',
    display_phone: '',
    distance: 1547.650441698189,
    userRating: 1,
  }],
};
