module.exports = [
  {
    id: '14886137290',
    title: 'Metallic waves',
    description: 'Walt Disney Concert Hall, Los Angeles, California',
    location: { lat: '34.055406', lon: '-118.250012' },
    tags: ['Walt Disney Concert Hall', 'LA Phil', 'philharmonic', 'abstract', 'entrance', 'steel', 'stainless', 'S Grand Ave', 'Banker Hill', 'downtown', 'downtown LA', 'dtla', 'music', 'concert', 'LAP', 'LAPO', 'orchestra', '111 South Grand Avenue', 'Frank Gehry', 'architecture', 'landmark', 'tourist', 'tourism', 'building', 'shiny', 'pretty', 'beautiful', 'modern', 'design', 'acoustics', 'Yasuhisa Toyota', 'reflection', 'exterior', 'matte', 'stainless steel', 'mirror', 'polished', 'concave', 'site', 'attraction', 'contemporary', 'color', 'blue', 'orange', 'tones', 'lines', 'geometric', 'squares', 'rectangles', 'perspective', 'tone', 'wall', 'urban', 'city', 'yellow', 'architect', 'planes', 'Pentax', 'K-5 II s', 'wide', 'angle', 'street', 'blocks', 'chrome', 'gold', 'metal', 'light', 'curve', 'simplicity', 'minimalism', 'elegant', 'simple', 'minimal'],
    srcPath: 'https://farm6.staticflickr.com/5553/14886137290_cfae123b41.jpg',
  }, {
    id: '4830521370',
    title: 'MyMuse',
    description: "<a href=\"http://bighugelabs.com/onblack.php?id=4830521370&amp;size=large\" rel=\"nofollow\">View Large On Black</a>\n\nThe reason I am calling this shot &quot;MyMuse&quot; is because I find myself constantly coming back to shots I took at the Getty Center in Los Angeles as a source of images.  I have been to the Getty Center twice in my life, last time this past April, and since I live on the east coast of the USA, I don't get that many opportunities to go.  The day I was there was absolutely perfect for shooting; a crisp clear day, combined with an amazing setting and amazing architecture, it was a little like heaven, at least for us shutter bugs.  Anyway, I took more pictures than I care to divulge that day.  So after taking a short break, I felt the need to go back and post another shot from that session.  I have made a small set of my other posts, <a href=\"http://www.flickr.com/photos/14977263@N04/sets/72157624460545869/\">GettyCenter</a>, and if you want to visit the real thing (on line at least) see the following link, <a href=\"http://www.getty.edu/\" rel=\"nofollow\">www.getty.edu/</a>.  Here is a short description of the museum from the website, it is all true;\n\n&quot;The Getty Center in Los Angeles presents the Getty's collection of Western art from the Middle Ages to the present against a backdrop of dramatic architecture, tranquil gardens, and breathtaking views.&quot;\n\nFinally, I will be posting more shots from that session in the coming days, my goal is to make them all unique, to show the range of the place itself.",
    location: { lat: '34.053489', lon: '-118.245323' },
    tags: ['la', 'los angeles', 'outside', 'graphic', 'gettycenter', 'getty', 'geometry', 'architecture', 'abstract', 'white', 'blue', 'perspective', 'nikon', 'sky', 'slats', 'wesbs', 'lines', 'curves', 'angles'],
    srcPath: 'https://farm5.staticflickr.com/4080/4830521370_e79a805db0.jpg',
  }, {
    id: '5368690851',
    title: 'Starry Eyed Surprise',
    description: '<a href="http://bighugelabs.com/onblack.php?id=5368690851&amp;size=large" rel="nofollow">View On Black</a>\n\nLong Exposure + Focus + De-Focus + Pull Back with a Zoom Lens looking at downtown LA from the Griffith Observatory...',
    location: { lat: '34.118230', lon: '-118.300080' },
    tags: ['Los Angles', 'Downtown', 'Observatory', 'cool', 'cool2', 'cool3', 'cool4', 'uncool', 'cool5', 'cool6 for AIV_Photography', 'cool7 for Rose', 'Icebox Cool'],
    srcPath: 'https://farm6.staticflickr.com/5283/5368690851_e6a0eb3660.jpg',
  }, {
    id: '1704505597',
    title: 'After the sun has gone - Totland Pier, Isle of Wight',
    description: 'This shot is one of several available as a canvas print in my galleries at canvasprintsonline.com, read here for more info <a href="http://www.flickr.com/photos/s0ulsurfing/3878251160/">www.flickr.com/photos/s0ulsurfing/3878251160/</a>\n\nFor everything else, you can visit <b><a href="http://www.jasonswain.co.uk/" rel="nofollow">My Website</a></b> ',
    location: { lat: '50.684386', lon: '-1.544394' },
    tags: ['s0ulsurfing', '2007', 'isle of wight', 'isle', 'wight', 'island', 'totland bay', 'totland', 'Totland Pier', 'vectis', 'bay', 'beach', 'coast', 'coastal', 'coastline', 'sea', 'water', 'ocean', 'shore', 'shoreline', 'seascape', 'blue', 'shadow', 'silhouette', 'light', 'sigma10-20', '10mm', 'wide', 'wide-angle', 'sunset', 'sun', 'sundown', 'dusk', 'evening', 'twilight', 'sky', 'skies', 'cloud', 'clouds', 'patterns', 'weather', 'EOW', 'infinestyle', 'mood', 'moody', 'dark', 'lo-light', 'low-light', 'composition', 'wow', 'beautiful', 'calm', 'calming', 'Nephology', 'meteorology', 'nube', 'fluffy', 'canvas prints', 'canvas', 'canvas art', 'giclee canvas prints', 'isle of wight attractions', 'isle of wight attraction', 'attraction', 'tourist', 'tourism', 'holiday', 'holidays', 'sights', 'sight-seeing', 'visitor attraction'],
    srcPath: 'https://farm3.staticflickr.com/2041/1704505597_d47559cd47.jpg',
  }, {
    id: '14876241160',
    title: 'Hidden entrance',
    description: 'Walt Disney Concert Hall, Los Angeles, California',
    location: { lat: '34.055406', lon: '-118.250012' },
    tags: ['Walt Disney Concert Hall', 'LA Phil', 'philharmonic', 'abstract', 'door', 'hidden', 'entrance', 'shine', 'steel', 'stainless', 'S Grand Ave', 'Banker Hill', 'downtown', 'downtown LA', 'dtla', 'music', 'concert', 'LAP', 'LAPO', 'orchestra', '111 South Grand Avenue', 'Frank Gehry', 'architecture', 'landmark', 'tourist', 'tourism', 'building', 'shiny', 'pretty', 'beautiful', 'modern', 'design', 'acoustics', 'Yasuhisa Toyota', 'reflection', 'exterior', 'matte', 'stainless steel', 'mirror', 'polished', 'concave', 'site', 'attraction', 'contemporary', 'color', 'blue', 'orange', 'tones', 'lines', 'geometric', 'squares', 'rectangles', 'perspective', 'tone', 'wall', 'urban', 'city', 'yellow', 'architect', 'planes', 'Pentax', 'K-5 II s', 'wide', 'angle', 'street', 'blocks', 'chrome', 'gold', 'metal', 'light', 'curve', 'simplicity', 'minimalism', 'elegant', 'simple', 'minimal'],
    srcPath: 'https://farm4.staticflickr.com/3894/14876241160_183c1897c7.jpg',
  }, {
    id: '15211220300',
    title: 'Urban Light',
    description: 'Processed with HDR Efex Pro.',
    location: { lat: '34.063022', lon: '-118.359200' },
    tags: ['Chris Burden', 'HDR', 'HDR Efex Pro', 'LACMA', 'Los Angeles', 'Urban Light', 'Wilshire Blvd.', 'architecture', 'art', 'blue hour', 'buildings', 'exhibit', 'lamps', 'light', 'lights', 'museum', 'night', 'wide angle'],
    srcPath: 'https://farm4.staticflickr.com/3924/15211220300_3d3c132456.jpg',
  }, {
    id: '4581449084',
    title: 'the escape',
    description: "Thank you Big Cat Rock <a href=\"http://www.flickr.com/photos/big_rock_cat/\">www.flickr.com/photos/big_rock_cat/</a> for the testimonial. It is so appreciated!\n\nThank you Daniela Duncan for setting up a gallery of just my images. What an honor! <a href=\"http://www.flickr.com/photos/dd-photography/galleries/72157623868584801/\">www.flickr.com/photos/dd-photography/galleries/7215762386...</a>\n\nToday marks one year that I've been on Flickr. It's been such fun ride and I've meet some great people. I thought I'd share a few highlights along the way.\n\n<a href=\"http://bighugelabs.com/onblack.php?id=4581449084&amp;size=large\" rel=\"nofollow\">View large on black</a>\n\n",
    location: { lat: '34.053489', lon: '-118.245323' },
    tags: ['los', 'angeles', 'california', 'subway', 'tunnel', 'silhouettes', 'out', 'this', 'world', 'escape', 'walking', 'bright', 'light', 'path', 'rail', 'glow', 'uphill', 'alien', 'architecture'],
    srcPath: 'https://farm5.staticflickr.com/4003/4581449084_3f882f0249.jpg',
  }, {
    id: '4604011811',
    title: 'colors of the night',
    description: "Here's another one from the other night with my new lens. Is it Friday yet?\n\nI try to only say this on the ones that need it, but this one should really be viewed <a href=\"http://bighugelabs.com/onblack.php?id=4604011811&amp;size=large\" rel=\"nofollow\">large!</a>",
    location: { lat: '34.053489', lon: '-118.245323' },
    tags: ['colors', 'night', 'downtown', 'los', 'angeles', 'california', 'shot', 'after', 'dark', 'buildings', 'water', 'reflections', 'sculpture', 'windows', 'office', 'architecture', 'ghery', 'disney', 'hall', 'lights', 'city', 'wide', 'angle', 'clear'],
    srcPath: 'https://farm2.staticflickr.com/1341/4604011811_900476aa02.jpg',
  }, {
    id: '4578569361',
    title: 'lighting the station',
    description: 'Union Station in Los Angeles after hours.',
    location: { lat: '34.053489', lon: '-118.245323' },
    tags: ['union', 'station', 'los', 'angeles', 'night', 'shot', 'lights', 'ceiling', 'after', 'dark', 'arch', 'windows', 'glow', 'empty', 'up', 'architecture', 'california', 'reflections', 'alien'],
    srcPath: 'https://farm5.staticflickr.com/4001/4578569361_647a285f1b.jpg',
  }, {
    id: '6553420711',
    title: 'fountains',
    description: '',
    location: { lat: '34.057672', lon: '-118.249894' },
    tags: ['TS-E 17mm f/4L', 'canon', 'EOS 5D Mark II', 'Eric Lo', 'photography', 'cityscape', 'landscape', 'night', 'midnight', 'reflection', 'skyline', 'architecture', 'building', 'water', 'fountain', 'LADWP', 'moat', 'wide angle', 'long exposure', 'downtown', 'DTLA', 'los angeles', 'california', 'united states', 'usa'],
    srcPath: 'https://farm8.staticflickr.com/7144/6553420711_bb8ed82a61.jpg',
  },
];
