module.exports = [
  {
    id: 'lJAGnYzku5zSaLnQ_T6_GQ',
    alias: 'brendas-french-soul-food-san-francisco',
    name: 'Brenda\'s French Soul Food',
    image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/YT8ho02lCT6Ubu3vx8uCaw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/brendas-french-soul-food-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 9280,
    categories: [
      {
        alias: 'breakfast_brunch',
        title: 'Breakfast & Brunch',
      },
      {
        alias: 'french',
        title: 'French',
      },
      {
        alias: 'soulfood',
        title: 'Soul Food',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 37.7829016035273,
      longitude: -122.419043442957,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '652 Polk St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94102',
      country: 'US',
      state: 'CA',
      display_address: [
        '652 Polk St',
        'San Francisco, CA 94102',
      ],
    },
    phone: '+14153458100',
    display_phone: '(415) 345-8100',
    distance: 1901.257604763642,
  },
  {
    id: 'WavvLdfdP6g8aZTtbBQHTw',
    alias: 'gary-danko-san-francisco',
    name: 'Gary Danko',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/NCX50ST3Hjg7y8wTcwQXog/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/gary-danko-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 4807,
    categories: [
      {
        alias: 'newamerican',
        title: 'American (New)',
      },
      {
        alias: 'french',
        title: 'French',
      },
      {
        alias: 'wine_bars',
        title: 'Wine Bars',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 37.80587,
      longitude: -122.42058,
    },
    transactions: [],
    price: '$$$$',
    location: {
      address1: '800 N Point St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94109',
      country: 'US',
      state: 'CA',
      display_address: [
        '800 N Point St',
        'San Francisco, CA 94109',
      ],
    },
    phone: '+14157492060',
    display_phone: '(415) 749-2060',
    distance: 4328.543432438436,
  },
  {
    id: 'ri7UUYmx21AgSpRsf4-9QA',
    alias: 'tartine-bakery-and-cafe-san-francisco',
    name: 'Tartine Bakery & Cafe',
    image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/vTLu8G86IqIazm7BRqIH4g/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/tartine-bakery-and-cafe-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 7196,
    categories: [
      {
        alias: 'bakeries',
        title: 'Bakeries',
      },
      {
        alias: 'cafes',
        title: 'Cafes',
      },
      {
        alias: 'desserts',
        title: 'Desserts',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 37.7614250022004,
      longitude: -122.424051321456,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '600 Guerrero St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94110',
      country: 'US',
      state: 'CA',
      display_address: [
        '600 Guerrero St',
        'San Francisco, CA 94110',
      ],
    },
    phone: '+14154872600',
    display_phone: '(415) 487-2600',
    distance: 759.4971828046934,
  },
  {
    id: 'oT08T3Vpn1I7jDmrBBRMTw',
    alias: 'house-of-prime-rib-san-francisco',
    name: 'House of Prime Rib',
    image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/HLrjaMoAgYSac0vx71YpCA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/house-of-prime-rib-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 6326,
    categories: [
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
      {
        alias: 'steak',
        title: 'Steakhouses',
      },
      {
        alias: 'wine_bars',
        title: 'Wine Bars',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 37.79338,
      longitude: -122.4225,
    },
    transactions: [],
    price: '$$$',
    location: {
      address1: '1906 Van Ness Ave',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94109',
      country: 'US',
      state: 'CA',
      display_address: [
        '1906 Van Ness Ave',
        'San Francisco, CA 94109',
      ],
    },
    phone: '+14158854605',
    display_phone: '(415) 885-4605',
    distance: 2936.828852047877,
  },
  {
    id: 'Xg-FyjVKAN70LO4u4Z1ozg',
    alias: 'hog-island-oyster-co-san-francisco',
    name: 'Hog Island Oyster Co',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/sSxgesuVoFD1_5w6FOoouQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/hog-island-oyster-co-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 5097,
    categories: [
      {
        alias: 'seafood',
        title: 'Seafood',
      },
      {
        alias: 'seafoodmarkets',
        title: 'Seafood Markets',
      },
      {
        alias: 'raw_food',
        title: 'Live/Raw Food',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 37.795831,
      longitude: -122.393303,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '1 Ferry Bldg',
      address2: '',
      address3: 'Shop 11',
      city: 'San Francisco',
      zip_code: '94111',
      country: 'US',
      state: 'CA',
      display_address: [
        '1 Ferry Bldg',
        'Shop 11',
        'San Francisco, CA 94111',
      ],
    },
    phone: '+14153917117',
    display_phone: '(415) 391-7117',
    distance: 4403.93022179265,
  },
  {
    id: 'PsY5DMHxa5iNX_nX0T-qPA',
    alias: 'kokkari-estiatorio-san-francisco',
    name: 'Kokkari Estiatorio',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/hL5JQzUDA06eqvmUtdUqZA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/kokkari-estiatorio-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 4061,
    categories: [
      {
        alias: 'greek',
        title: 'Greek',
      },
      {
        alias: 'mediterranean',
        title: 'Mediterranean',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 37.796996,
      longitude: -122.399661,
    },
    transactions: [],
    price: '$$$',
    location: {
      address1: '200 Jackson St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94111',
      country: 'US',
      state: 'CA',
      display_address: [
        '200 Jackson St',
        'San Francisco, CA 94111',
      ],
    },
    phone: '+14159810983',
    display_phone: '(415) 981-0983',
    distance: 4136.929077533057,
  },
  {
    id: 'ZoZjbOYR-apY8XvommlNUA',
    alias: 'the-house-san-francisco',
    name: 'The House',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/K48sSeIuHURatMBrSTfOTg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/the-house-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 4299,
    categories: [
      {
        alias: 'asianfusion',
        title: 'Asian Fusion',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 37.7986203,
      longitude: -122.4070251,
    },
    transactions: [
      'restaurant_reservation',
    ],
    price: '$$$',
    location: {
      address1: '1230 Grant Ave',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94133',
      country: 'US',
      state: 'CA',
      display_address: [
        '1230 Grant Ave',
        'San Francisco, CA 94133',
      ],
    },
    phone: '+14159868612',
    display_phone: '(415) 986-8612',
    distance: 3922.032714477108,
  },
  {
    id: 'eYXwVR4mMAjzkJnm5wneHQ',
    alias: 'burma-superstar-san-francisco-2',
    name: 'Burma Superstar',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/UaR8ZJlXHHWO3t-47tp0jg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/burma-superstar-san-francisco-2?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 6119,
    categories: [
      {
        alias: 'burmese',
        title: 'Burmese',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 37.782787322998,
      longitude: -122.462539672852,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '309 Clement St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94118',
      country: 'US',
      state: 'CA',
      display_address: [
        '309 Clement St',
        'San Francisco, CA 94118',
      ],
    },
    phone: '+14153872147',
    display_phone: '(415) 387-2147',
    distance: 3469.4770751183487,
  },
  {
    id: 'ttarnopezxmp2ROB1N2PaA',
    alias: 'nopa-san-francisco',
    name: 'Nopa',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/M8lkaDkG8GChJ1qvXhtLNw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/nopa-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 4707,
    categories: [
      {
        alias: 'newamerican',
        title: 'American (New)',
      },
      {
        alias: 'modern_european',
        title: 'Modern European',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 37.774905,
      longitude: -122.437506,
    },
    transactions: [],
    price: '$$$',
    location: {
      address1: '560 Divisadero St',
      address2: null,
      address3: '',
      city: 'San Francisco',
      zip_code: '94117',
      country: 'US',
      state: 'CA',
      display_address: [
        '560 Divisadero St',
        'San Francisco, CA 94117',
      ],
    },
    phone: '+14158648643',
    display_phone: '(415) 864-8643',
    distance: 1167.0280822115808,
  },
  {
    id: 'M0JTO3oyu6gxh1mfFjU-dA',
    alias: 'san-tung-san-francisco-2',
    name: 'San Tung',
    image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/bBKx0vw4X5IGlEbUPYKJFw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/san-tung-san-francisco-2?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 6042,
    categories: [
      {
        alias: 'chinese',
        title: 'Chinese',
      },
      {
        alias: 'chicken_wings',
        title: 'Chicken Wings',
      },
      {
        alias: 'noodles',
        title: 'Noodles',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 37.76367,
      longitude: -122.46896,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '1031 Irving St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94122',
      country: 'US',
      state: 'CA',
      display_address: [
        '1031 Irving St',
        'San Francisco, CA 94122',
      ],
    },
    phone: '+14152420828',
    display_phone: '(415) 242-0828',
    distance: 3609.400586996837,
  },
  {
    id: 'SGRmnarrNuVEsAjYdEoA0w',
    alias: 'el-farolito-san-francisco-2',
    name: 'El Farolito',
    image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/OPnKCvgBR2-lQ1-yahrpiA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/el-farolito-san-francisco-2?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 4381,
    categories: [
      {
        alias: 'mexican',
        title: 'Mexican',
      },
      {
        alias: 'seafood',
        title: 'Seafood',
      },
      {
        alias: 'sandwiches',
        title: 'Sandwiches',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 37.75265,
      longitude: -122.41812,
    },
    transactions: [],
    price: '$',
    location: {
      address1: '2779 Mission St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94110',
      country: 'US',
      state: 'CA',
      display_address: [
        '2779 Mission St',
        'San Francisco, CA 94110',
      ],
    },
    phone: '+14158247877',
    display_phone: '(415) 824-7877',
    distance: 1862.4231381622099,
  },
  {
    id: 'hqQoVK0vadOX7_4gN1sh3g',
    alias: 'saigon-sandwich-san-francisco',
    name: 'Saigon Sandwich',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/lVyf1pn7ft4YzO2n4z7Exg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/saigon-sandwich-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 3006,
    categories: [
      {
        alias: 'vietnamese',
        title: 'Vietnamese',
      },
      {
        alias: 'sandwiches',
        title: 'Sandwiches',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 37.7831519576568,
      longitude: -122.417318022037,
    },
    transactions: [],
    price: '$',
    location: {
      address1: '560 Larkin St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94102',
      country: 'US',
      state: 'CA',
      display_address: [
        '560 Larkin St',
        'San Francisco, CA 94102',
      ],
    },
    phone: '+14154745698',
    display_phone: '(415) 474-5698',
    distance: 1994.6728502467226,
  },
  {
    id: 'gqVl3RprESEqkIPeJH0yOg',
    alias: 'zazie-san-francisco',
    name: 'Zazie',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/hBFLvIMkEyxEjxk6iAtLvw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/zazie-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 3932,
    categories: [
      {
        alias: 'breakfast_brunch',
        title: 'Breakfast & Brunch',
      },
      {
        alias: 'french',
        title: 'French',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 37.765244,
      longitude: -122.4501138,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '941 Cole St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94117',
      country: 'US',
      state: 'CA',
      display_address: [
        '941 Cole St',
        'San Francisco, CA 94117',
      ],
    },
    phone: '+14155645332',
    display_phone: '(415) 564-5332',
    distance: 1940.6466017691776,
  },
  {
    id: 'n6L5VIGunR51-D55C-eYeQ',
    alias: 'foreign-cinema-san-francisco',
    name: 'Foreign Cinema',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/cw5y2LSOIE-EVNjKK_d7SQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/foreign-cinema-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 4407,
    categories: [
      {
        alias: 'breakfast_brunch',
        title: 'Breakfast & Brunch',
      },
      {
        alias: 'mediterranean',
        title: 'Mediterranean',
      },
      {
        alias: 'cocktailbars',
        title: 'Cocktail Bars',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 37.75637,
      longitude: -122.41925,
    },
    transactions: [],
    price: '$$$',
    location: {
      address1: '2534 Mission St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94110',
      country: 'US',
      state: 'CA',
      display_address: [
        '2534 Mission St',
        'San Francisco, CA 94110',
      ],
    },
    phone: '+14156487600',
    display_phone: '(415) 648-7600',
    distance: 1457.85944085646,
  },
  {
    id: '8dUaybEPHsZMgr1iKgqgMQ',
    alias: 'sotto-mare-oysteria-and-seafood-san-francisco',
    name: 'Sotto Mare Oysteria & Seafood',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/A5sqbVpCIMqUdae_TSMkjQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/sotto-mare-oysteria-and-seafood-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 3089,
    categories: [
      {
        alias: 'seafood',
        title: 'Seafood',
      },
      {
        alias: 'italian',
        title: 'Italian',
      },
      {
        alias: 'bars',
        title: 'Bars',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 37.79979,
      longitude: -122.40834,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '552 Green St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94133',
      country: 'US',
      state: 'CA',
      display_address: [
        '552 Green St',
        'San Francisco, CA 94133',
      ],
    },
    phone: '+14153983181',
    display_phone: '(415) 398-3181',
    distance: 4001.869559453432,
  },
  {
    id: 'MvAo0hj9FXOeNL5PwBZ0fQ',
    alias: 'mamas-on-washington-square-san-francisco',
    name: 'Mama\'s On Washington Square',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/ETJbHf1tlPkn5V-EKjsmLw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/mamas-on-washington-square-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 3851,
    categories: [
      {
        alias: 'breakfast_brunch',
        title: 'Breakfast & Brunch',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 37.801606,
      longitude: -122.409599,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '1701 Stockton St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94133',
      country: 'US',
      state: 'CA',
      display_address: [
        '1701 Stockton St',
        'San Francisco, CA 94133',
      ],
    },
    phone: '+14153626421',
    display_phone: '(415) 362-6421',
    distance: 4138.82301952994,
  },
  {
    id: '__I9HmtBMV4dDkEgT22V4g',
    alias: 'little-star-pizza-san-francisco',
    name: 'Little Star Pizza',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/C-lgf5TcabWh0YvlTAGGTw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/little-star-pizza-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 2725,
    categories: [
      {
        alias: 'pizza',
        title: 'Pizza',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 37.77753,
      longitude: -122.43798,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '846 Divisadero St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94117',
      country: 'US',
      state: 'CA',
      display_address: [
        '846 Divisadero St',
        'San Francisco, CA 94117',
      ],
    },
    phone: '+14154411118',
    display_phone: '(415) 441-1118',
    distance: 1416.3873915647416,
  },
  {
    id: 'mSMZJj2pFvttWLpcDmgrEA',
    alias: 'tonys-pizza-napoletana-san-francisco',
    name: 'Tony\'s Pizza Napoletana',
    image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/d8tM3JkgYW0roXBygLoSKg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/tonys-pizza-napoletana-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 4077,
    categories: [
      {
        alias: 'pizza',
        title: 'Pizza',
      },
      {
        alias: 'italian',
        title: 'Italian',
      },
      {
        alias: 'cocktailbars',
        title: 'Cocktail Bars',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 37.80032,
      longitude: -122.40894,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '1570 Stockton St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94133',
      country: 'US',
      state: 'CA',
      display_address: [
        '1570 Stockton St',
        'San Francisco, CA 94133',
      ],
    },
    phone: '+14158359888',
    display_phone: '(415) 835-9888',
    distance: 4028.1808186760663,
  },
  {
    id: 'f-m7-hyFzkf0HSEeQ2s-9A',
    alias: 'fog-harbor-fish-house-san-francisco-2',
    name: 'Fog Harbor Fish House',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/L-q1jmqFT5GQHW63GesQuQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/fog-harbor-fish-house-san-francisco-2?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 4252,
    categories: [
      {
        alias: 'seafood',
        title: 'Seafood',
      },
      {
        alias: 'bars',
        title: 'Bars',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 37.80873,
      longitude: -122.410428,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: 'Pier 39',
      address2: 'Ste A-202',
      address3: '',
      city: 'San Francisco',
      zip_code: '94133',
      country: 'US',
      state: 'CA',
      display_address: [
        'Pier 39',
        'Ste A-202',
        'San Francisco, CA 94133',
      ],
    },
    phone: '+14154212442',
    display_phone: '(415) 421-2442',
    distance: 4852.605407720572,
  },
  {
    id: 'PTFxtXS47ZVRCdZIrEWvGw',
    alias: 'golden-boy-pizza-san-francisco',
    name: 'Golden Boy Pizza',
    image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/FkqH-CWw5-PThWCF5NP2oQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/golden-boy-pizza-san-francisco?adjust_creative=WuafYso5hUYra52_Siwe3Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=WuafYso5hUYra52_Siwe3Q',
    review_count: 2917,
    categories: [
      {
        alias: 'pizza',
        title: 'Pizza',
      },
      {
        alias: 'italian',
        title: 'Italian',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 37.7997956,
      longitude: -122.4080729,
    },
    transactions: [],
    price: '$',
    location: {
      address1: '542 Green St',
      address2: '',
      address3: '',
      city: 'San Francisco',
      zip_code: '94133',
      country: 'US',
      state: 'CA',
      display_address: [
        '542 Green St',
        'San Francisco, CA 94133',
      ],
    },
    phone: '+14159829738',
    display_phone: '(415) 982-9738',
    distance: 4012.0206628297437,
  },
];
